# Generated by Django 3.2.7 on 2021-10-19 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mosaic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('base_img', models.ImageField(upload_to='base_images/')),
                ('granularity', models.IntegerField()),
                ('neighborhood_size', models.IntegerField()),
                ('fineness', models.IntegerField()),
                ('random_max', models.IntegerField()),
                ('w_sections', models.IntegerField()),
                ('h_sections', models.IntegerField()),
                ('rgb_weighting', models.JSONField()),
                ('mosaic_grid_data', models.JSONField()),
                ('opts', models.JSONField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordinate_x', models.IntegerField()),
                ('coordinate_y', models.IntegerField()),
                ('cooredinates', models.JSONField()),
                ('height', models.IntegerField()),
                ('width', models.IntegerField()),
                ('pinned', models.BooleanField()),
                ('priority', models.IntegerField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('mosaic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mosaic.mosaic')),
            ],
        ),
        migrations.CreateModel(
            name='Piece',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='pieces/')),
                ('mode', models.CharField(max_length=20)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('tags', models.ManyToManyField(related_name='pieces', to='mosaic.Tag')),
            ],
        ),
    ]
