# Generated by Django 3.2.7 on 2021-10-20 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mosaic', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section',
            old_name='cooredinates',
            new_name='coordinates',
        ),
        migrations.AddField(
            model_name='section',
            name='piece',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mosaic.piece'),
        ),
        migrations.AlterField(
            model_name='mosaic',
            name='base_img',
            field=models.ImageField(blank=True, upload_to='mosaic/base_images/'),
        ),
        migrations.AlterField(
            model_name='mosaic',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='mosaic',
            name='mosaic_grid_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='piece',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='piece',
            name='img',
            field=models.ImageField(upload_to='mosaic/pieces/'),
        ),
        migrations.AlterField(
            model_name='piece',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='pieces', to='mosaic.Tag'),
        ),
        migrations.AlterField(
            model_name='section',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
