# Generated by Django 3.2.7 on 2021-10-26 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mosaic', '0004_auto_20211022_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mosaic',
            name='h_sections',
        ),
        migrations.RemoveField(
            model_name='mosaic',
            name='w_sections',
        ),
        migrations.RemoveField(
            model_name='section',
            name='coordinates',
        ),
        migrations.RemoveField(
            model_name='section',
            name='height',
        ),
        migrations.RemoveField(
            model_name='section',
            name='width',
        ),
        migrations.AlterField(
            model_name='mosaic',
            name='fineness',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='mosaic',
            name='granularity',
            field=models.IntegerField(default=0.0625),
        ),
        migrations.AlterField(
            model_name='mosaic',
            name='neighborhood_size',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='mosaic',
            name='opts',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mosaic',
            name='random_max',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mosaic',
            name='rgb_weighting',
            field=models.JSONField(default=[1, 1, 1]),
        ),
    ]
