# Generated by Django 3.2.7 on 2021-10-26 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mosaic', '0005_auto_20211026_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mosaic',
            name='granularity',
            field=models.FloatField(default=0.0625),
        ),
    ]
